services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    ports:
      - "${SPRING_KEYCLOAK_PORT}:8080"
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${SPRING_KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${SPRING_KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: ${KEYCLOAK_DB}
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST}
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

    depends_on:
      - keycloak_postgres

  keycloak_postgres:
    image: postgres:16
    container_name: postgres_keycloak
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
  postgres:
    env_file:
      - .env
    image: postgres:16
    container_name: postgres_db_pedeai
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SPRING_DATABASE_NAME}
      POSTGRES_USER: ${SPRING_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  keycloak_data: