spring:
  application:
    name: pedeai
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class0-name: org.postgresql.Driver
